name: Tests

on:
  push:
    branches: [ development ]
  workflow_dispatch:
  pull_request:
    branches: [ development ]
  

env:
  FLUTTER_VERSION: '3.16.x'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get

  analyze:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: flutter analyze --fatal-infos

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: dart format --set-exit-if-changed .

  widget-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: flutter test

  build-android-and-upload:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev
      - run: flutter --disable-analytics
      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v3 # upload the app
        if: github.event_name == 'push' && github.ref == 'refs/heads/stable'
        with:
          name: bartalap-android
          path: build/app/outputs/apk/release/app-release.apk